#pragma once

#include <GL/glew.h>
//#include <glad/gl.h>//this is file generated by glad, but most tutorials have GL folder
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

// Include standard headers
#include <stdio.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <sstream>

namespace Helpers
{
	GLuint LoadShaders(const char* vertex_file_path, const char* fragment_file_path);
}